// actions
export const GET_PRODUCT_ATTRIBUTES = 'GET_PRODUCT_ATTRIBUTES'
export const GET_PRODUCT_ATTRIBUTE_CREATE = 'GET_PRODUCT_ATTRIBUTE_CREATE'
export const GET_PRODUCT_ATTRIBUTE_SHOW = 'GET_PRODUCT_ATTRIBUTE_SHOW'
export const GET_PRODUCT_ATTRIBUTE_UPDATE = 'GET_PRODUCT_ATTRIBUTE_UPDATE'
export const GET_PRODUCT_ATTRIBUTE_DELETE = 'GET_PRODUCT_ATTRIBUTE_DELETE'
export const GET_PRODUCT_CHECK_BEFORE_ATTRIBUTE_DELETE = 'GET_PRODUCT_CHECK_BEFORE_ATTRIBUTE_DELETE'

// mutations
export const SET_PRODUCT_ATTRIBUTES = 'SET_PRODUCT_ATTRIBUTES'
