// actions
export const GET_CUSTOMER_ATTRIBUTES = 'GET_CUSTOMER_ATTRIBUTES'
export const GET_CUSTOMER_ATTRIBUTE_CREATE = 'GET_CUSTOMER_ATTRIBUTE_CREATE'
export const GET_CUSTOMER_ATTRIBUTE_SHOW = 'GET_CUSTOMER_ATTRIBUTE_SHOW'
export const GET_CUSTOMER_ATTRIBUTE_UPDATE = 'GET_CUSTOMER_ATTRIBUTE_UPDATE'
export const GET_CUSTOMER_ATTRIBUTE_DELETE = 'GET_CUSTOMER_ATTRIBUTE_DELETE'
export const GET_CUSTOMER_CHECK_BEFORE_ATTRIBUTE_DELETE = 'GET_CUSTOMER_CHECK_BEFORE_ATTRIBUTE_DELETE'
export const GET_CUSTOMER_DETAILS = 'GET_CUSTOMER_DETAILS'

// mutations
export const SET_CUSTOMER_ATTRIBUTES = 'SET_CUSTOMER_ATTRIBUTES'
export const SET_CUSTOMER_DETAILS = 'SET_CUSTOMER_DETAILS'
