// actions
export const GET_CONTACT_ATTRIBUTES = 'GET_CONTACT_ATTRIBUTES'
export const GET_CONTACT_ATTRIBUTE_CREATE = 'GET_CONTACT_ATTRIBUTE_CREATE'
export const GET_CONTACT_ATTRIBUTE_SHOW = 'GET_CONTACT_ATTRIBUTE_SHOW'
export const GET_CONTACT_ATTRIBUTE_UPDATE = 'GET_CONTACT_ATTRIBUTE_UPDATE'
export const GET_CONTACT_ATTRIBUTE_DELETE = 'GET_CONTACT_ATTRIBUTE_DELETE'
export const GET_CONTACT_CHECK_BEFORE_ATTRIBUTE_DELETE = 'GET_CONTACT_CHECK_BEFORE_ATTRIBUTE_DELETE'

// mutations
export const SET_CONTACT_ATTRIBUTES = 'SET_CONTACT_ATTRIBUTES'
